// **********************************************************************
// Parsed By TarsParser(1.1.0), Generated By tars2node(20190529)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "QueryF.tars" by Server Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var assert    = require("assert");
var TarsStream = require("@tars/stream");
var TarsError  = require("@tars/rpc").error;
var _TARS_MODULE_A_ = require("./EndpointFTars.js");

var tars = tars || {};
module.exports.tars = tars;

tars.QueryFImp = function () { 
    this._name   = undefined;
    this._worker = undefined;
};

tars.QueryFImp.prototype.initialize = function () {};

tars.QueryFImp.prototype.onDispatch = function (current, funcName, binBuffer) { 
    if ("__" + funcName in this) {
        return this["__" + funcName](current, binBuffer);
    } else {
        return TarsError.SERVER.FUNC_NOT_FOUND;
    }
};

var __tars_QueryF$tars_ping$RE = function (_ret) {
    if (this.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || this.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = this.getRequestVersion();
        tup.writeInt32("", _ret);

        this.doResponse(tup.encode());
    } else {
        var os = new TarsStream.TarsOutputStream();
        os.writeInt32(0, _ret);

        this.doResponse(os.getBinBuffer());
    }
};

tars.QueryFImp.prototype.__tars_ping = function (current) {
    __tars_QueryF$tars_ping$RE.call(current, 0);

    return TarsError.SUCCESS;
};

tars.QueryFImp.prototype.findObjectById = function () {
    assert.fail("findObjectById function not implemented");
};

var __tars_QueryF$findObjectById$RE = function (_ret) {
    if (this.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || this.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = this.getRequestVersion();
        tup.writeList("", _ret);

        this.doResponse(tup.encode());
    } else {
        var os = new TarsStream.TarsOutputStream();
        os.writeList(0, _ret);

        this.doResponse(os.getBinBuffer());
    }
};

tars.QueryFImp.prototype.__findObjectById = function (current, binBuffer) {
    var id = null;

    if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = current.getRequestVersion();
        tup.decode(binBuffer);
        id = tup.readString("id");
    } else {
        var is = new TarsStream.TarsInputStream(binBuffer);
        id = is.readString(1, true, "");
    }

    current.sendResponse = __tars_QueryF$findObjectById$RE;

    this.findObjectById(current, id);

    return TarsError.SUCCESS;
};

tars.QueryFImp.prototype.findObjectById4Any = function () {
    assert.fail("findObjectById4Any function not implemented");
};

var __tars_QueryF$findObjectById4Any$RE = function (_ret, activeEp, inactiveEp) {
    if (this.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || this.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = this.getRequestVersion();
        tup.writeInt32("", _ret);
        tup.writeList("activeEp", activeEp);
        tup.writeList("inactiveEp", inactiveEp);

        this.doResponse(tup.encode());
    } else {
        var os = new TarsStream.TarsOutputStream();
        os.writeInt32(0, _ret);
        os.writeList(2, activeEp);
        os.writeList(3, inactiveEp);

        this.doResponse(os.getBinBuffer());
    }
};

tars.QueryFImp.prototype.__findObjectById4Any = function (current, binBuffer) {
    var id = null;
    var activeEp = null;
    var inactiveEp = null;

    if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = current.getRequestVersion();
        tup.decode(binBuffer);
        id = tup.readString("id");
        activeEp = tup.readList("activeEp", TarsStream.List(_TARS_MODULE_A_.tars.EndpointF), new TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
        inactiveEp = tup.readList("inactiveEp", TarsStream.List(_TARS_MODULE_A_.tars.EndpointF), new TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
    } else {
        var is = new TarsStream.TarsInputStream(binBuffer);
        id = is.readString(1, true, "");
        activeEp = is.readList(2, false, TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
        inactiveEp = is.readList(3, false, TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
    }

    current.sendResponse = __tars_QueryF$findObjectById4Any$RE;

    this.findObjectById4Any(current, id, activeEp, inactiveEp);

    return TarsError.SUCCESS;
};

tars.QueryFImp.prototype.findObjectById4All = function () {
    assert.fail("findObjectById4All function not implemented");
};

var __tars_QueryF$findObjectById4All$RE = function (_ret, activeEp, inactiveEp) {
    if (this.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || this.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = this.getRequestVersion();
        tup.writeInt32("", _ret);
        tup.writeList("activeEp", activeEp);
        tup.writeList("inactiveEp", inactiveEp);

        this.doResponse(tup.encode());
    } else {
        var os = new TarsStream.TarsOutputStream();
        os.writeInt32(0, _ret);
        os.writeList(2, activeEp);
        os.writeList(3, inactiveEp);

        this.doResponse(os.getBinBuffer());
    }
};

tars.QueryFImp.prototype.__findObjectById4All = function (current, binBuffer) {
    var id = null;
    var activeEp = null;
    var inactiveEp = null;

    if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = current.getRequestVersion();
        tup.decode(binBuffer);
        id = tup.readString("id");
        activeEp = tup.readList("activeEp", TarsStream.List(_TARS_MODULE_A_.tars.EndpointF), new TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
        inactiveEp = tup.readList("inactiveEp", TarsStream.List(_TARS_MODULE_A_.tars.EndpointF), new TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
    } else {
        var is = new TarsStream.TarsInputStream(binBuffer);
        id = is.readString(1, true, "");
        activeEp = is.readList(2, false, TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
        inactiveEp = is.readList(3, false, TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
    }

    current.sendResponse = __tars_QueryF$findObjectById4All$RE;

    this.findObjectById4All(current, id, activeEp, inactiveEp);

    return TarsError.SUCCESS;
};

tars.QueryFImp.prototype.findObjectByIdInSameGroup = function () {
    assert.fail("findObjectByIdInSameGroup function not implemented");
};

var __tars_QueryF$findObjectByIdInSameGroup$RE = function (_ret, activeEp, inactiveEp) {
    if (this.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || this.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = this.getRequestVersion();
        tup.writeInt32("", _ret);
        tup.writeList("activeEp", activeEp);
        tup.writeList("inactiveEp", inactiveEp);

        this.doResponse(tup.encode());
    } else {
        var os = new TarsStream.TarsOutputStream();
        os.writeInt32(0, _ret);
        os.writeList(2, activeEp);
        os.writeList(3, inactiveEp);

        this.doResponse(os.getBinBuffer());
    }
};

tars.QueryFImp.prototype.__findObjectByIdInSameGroup = function (current, binBuffer) {
    var id = null;
    var activeEp = null;
    var inactiveEp = null;

    if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = current.getRequestVersion();
        tup.decode(binBuffer);
        id = tup.readString("id");
        activeEp = tup.readList("activeEp", TarsStream.List(_TARS_MODULE_A_.tars.EndpointF), new TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
        inactiveEp = tup.readList("inactiveEp", TarsStream.List(_TARS_MODULE_A_.tars.EndpointF), new TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
    } else {
        var is = new TarsStream.TarsInputStream(binBuffer);
        id = is.readString(1, true, "");
        activeEp = is.readList(2, false, TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
        inactiveEp = is.readList(3, false, TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
    }

    current.sendResponse = __tars_QueryF$findObjectByIdInSameGroup$RE;

    this.findObjectByIdInSameGroup(current, id, activeEp, inactiveEp);

    return TarsError.SUCCESS;
};

tars.QueryFImp.prototype.findObjectByIdInSameStation = function () {
    assert.fail("findObjectByIdInSameStation function not implemented");
};

var __tars_QueryF$findObjectByIdInSameStation$RE = function (_ret, activeEp, inactiveEp) {
    if (this.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || this.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = this.getRequestVersion();
        tup.writeInt32("", _ret);
        tup.writeList("activeEp", activeEp);
        tup.writeList("inactiveEp", inactiveEp);

        this.doResponse(tup.encode());
    } else {
        var os = new TarsStream.TarsOutputStream();
        os.writeInt32(0, _ret);
        os.writeList(3, activeEp);
        os.writeList(4, inactiveEp);

        this.doResponse(os.getBinBuffer());
    }
};

tars.QueryFImp.prototype.__findObjectByIdInSameStation = function (current, binBuffer) {
    var id = null;
    var sStation = null;
    var activeEp = null;
    var inactiveEp = null;

    if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = current.getRequestVersion();
        tup.decode(binBuffer);
        id = tup.readString("id");
        sStation = tup.readString("sStation");
        activeEp = tup.readList("activeEp", TarsStream.List(_TARS_MODULE_A_.tars.EndpointF), new TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
        inactiveEp = tup.readList("inactiveEp", TarsStream.List(_TARS_MODULE_A_.tars.EndpointF), new TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
    } else {
        var is = new TarsStream.TarsInputStream(binBuffer);
        id = is.readString(1, true, "");
        sStation = is.readString(2, true, "");
        activeEp = is.readList(3, false, TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
        inactiveEp = is.readList(4, false, TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
    }

    current.sendResponse = __tars_QueryF$findObjectByIdInSameStation$RE;

    this.findObjectByIdInSameStation(current, id, sStation, activeEp, inactiveEp);

    return TarsError.SUCCESS;
};

tars.QueryFImp.prototype.findObjectByIdInSameSet = function () {
    assert.fail("findObjectByIdInSameSet function not implemented");
};

var __tars_QueryF$findObjectByIdInSameSet$RE = function (_ret, activeEp, inactiveEp) {
    if (this.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || this.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = this.getRequestVersion();
        tup.writeInt32("", _ret);
        tup.writeList("activeEp", activeEp);
        tup.writeList("inactiveEp", inactiveEp);

        this.doResponse(tup.encode());
    } else {
        var os = new TarsStream.TarsOutputStream();
        os.writeInt32(0, _ret);
        os.writeList(3, activeEp);
        os.writeList(4, inactiveEp);

        this.doResponse(os.getBinBuffer());
    }
};

tars.QueryFImp.prototype.__findObjectByIdInSameSet = function (current, binBuffer) {
    var id = null;
    var setId = null;
    var activeEp = null;
    var inactiveEp = null;

    if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
        var tup = new TarsStream.UniAttribute();
        tup.tupVersion = current.getRequestVersion();
        tup.decode(binBuffer);
        id = tup.readString("id");
        setId = tup.readString("setId");
        activeEp = tup.readList("activeEp", TarsStream.List(_TARS_MODULE_A_.tars.EndpointF), new TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
        inactiveEp = tup.readList("inactiveEp", TarsStream.List(_TARS_MODULE_A_.tars.EndpointF), new TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
    } else {
        var is = new TarsStream.TarsInputStream(binBuffer);
        id = is.readString(1, true, "");
        setId = is.readString(2, true, "");
        activeEp = is.readList(3, false, TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
        inactiveEp = is.readList(4, false, TarsStream.List(_TARS_MODULE_A_.tars.EndpointF));
    }

    current.sendResponse = __tars_QueryF$findObjectByIdInSameSet$RE;

    this.findObjectByIdInSameSet(current, id, setId, activeEp, inactiveEp);

    return TarsError.SUCCESS;
};





